config/routes.rb
Rails.application.routes.draw do
  resources :entries

  root 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :entry_type
  validates :title, presence: true
end

app/models/entry_type.rb
class EntryType < ActiveRecord::Base
  has_many :entries
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to entries_path
    else
      render :new
    end
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update_attributes(entry_params)
      redirect_to entries_path
    else
      render :edit
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to entries_path
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :body, :entry_type_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
  <% if @entry.errors.any? %>
    <div class='errors'>
      <h2>Uh oh, errors!</h2>
      <% @entry.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :entry_type, 'What type of entry is this?' %>
    <%= f.collection_select :entry_type_id, EntryType.all, :id, :name %>
  </div>

  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class='field'>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class='field'>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= render 'form' %>

app/views/entries/index.html.erb
<h1>List of Entries</h1>

<p><%= link_to 'New entry', new_entry_path %></p>

<br>

<% @entries.each do |entry| %>
  <h3><%= entry.entry_type.name %>: <%= entry.title %></h3>

  <p><%= simple_format(entry.body) %></p>

  <p>
    <%= link_to 'Edit', edit_entry_path(entry) %>
    *
    <%= link_to 'Delete', entry_path(entry), method: :delete %>
  </p>

  <br>
  <br>
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>